config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :shoes

end

app/models/shoe.rb
class Shoe < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController

def index
  @shoe = Shoe.new
  @shoes = Shoe.all
end

  def create
    @shoe = Shoe.create(shoe_params)
    if @shoe.save
      redirect_to shoes_path
    else
      render :index
    end
  end

def show
  @shoe = Shoe.find(params[:id])
end

def edit
  @shoe = Shoe.find(params[:id])
end

def update
  @shoe = Shoe.find(params[:id])
  @shoe.update_attributes!(shoe_params)

  redirect_to shoes_path
end

def destroy
  @shoe = Shoe.find(params[:id]).delete
  redirect_to shoes_path
end

  private

  def shoe_params
    params.require(:shoe).permit(:shoe_type, :heel)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCrudShoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shoes/edit.html.erb
<%= form_for @shoe do |f| %>
  <p>
    <%= f.label :shoe_type %>
    <%= f.text_field :shoe_type %>
  </p>
  <p>
    <%= f.label :heel %>
    <%= f.text_field :heel %>
  </p>
  <p>
    <%= f.submit 'Update Shoes' %>
  </p>
<% end %>

app/views/shoes/index.html.erb
<%= form_for @shoe do |f| %>
  <p>
    <%= f.label :shoe_type %>
    <%= f.text_field :shoe_type %>
  </p>
  <p>
    <%= f.label :heel %>
    <%= f.text_field :heel %>
  </p>
  <p>
    <%= f.submit 'Create Shoes' %>
  </p>
<% end %>

<% @shoes.each do |shoe| %>
  <ul>
    <li>
      <%= link_to "#{shoe.shoe_type}", shoe_path(shoe) %>
      <br>
      <%= shoe.heel %>
    </li>
  </ul>
<% end %>

app/views/shoes/show.html.erb
<ul>
  <li>
    <%= @shoe.shoe_type %>
    <br>
    <%= @shoe.heel %>
  </li>
</ul>

<%= link_to 'Edit', edit_shoe_path %>
<%= link_to 'Delete', shoe_path, method: :delete %>

app/views/welcome/index.html.erb
<h2>Welcome</h2>

<%= link_to 'Add Shoes', shoes_path %>